# Generated by Django 4.1.4 on 2022-12-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("back", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="category",
            field=models.CharField(
                choices=[("아파트", "Apartment"), ("단독 주택", "House"), ("원룸", "Studio")],
                default="Apartment",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
